# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Deploy Artifacts
on:
#  push:
#    branches:
#    paths:
#    - 'src/**'
#    - 'pom.xml'
#    - '.github/workflows/*'
  release:
    types:
    - published
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to Github Package Registry
      # https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables
      # https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions#github-context
      # https://stackoverflow.com/questions/57711558/deploy-to-github-package-registry-from-github-action#answer-58109063
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Note: disable staging integration (buildsupport-staging.skip=true),
        # it will push the artifacts to the nexus's repository which isn't owned by us
        mvn clean deploy -X \
          -Dbuildsupport-staging.skip=true \
          -Dmaven.test.skip=true \
          --settings .github/workflows/maven-settings.xml \
          --file pom.xml
